name: 'Node 12 Template Action'
description: 'Una primera prueba de GitHub Actions'
author: 'GitHub'
inputs:
  myVar:
    description: 'Una entrada cualquiera'
    default: 'world'
runs:
  using: 'node12'
  main: 'lib/main.js'
