on:
  pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            request = require("@octokit/request")
            const diff_url = context.payload.pull_request.diff_url
            const result = await request( diff_url )
            console.log( result )

